CREATE TABLE IF NOT EXISTS employer (
  id SERIAL PRIMARY KEY,
  fname VARCHAR(30) NOT NULL,
  lname VARCHAR(20) NOT NULL,
  tel VARCHAR[],
  description TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS worker (
  id SERIAL PRIMARY KEY,
  fname VARCHAR(30) NOT NULL,
  lname VARCHAR(20) NOT NULL,
  tel VARCHAR[],
  iban VARCHAR(34),
  description TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price (
  id SERIAL PRIMARY KEY,
  fulltime NUMERIC(12,2) NOT NULL,
  halftime NUMERIC(12,2) NOT NULL,
  overtime NUMERIC(12,2) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job (
  id SERIAL PRIMARY KEY,
  employer_id INT NOT NULL REFERENCES employer(id) ON DELETE CASCADE,
  price_id INT NOT NULL REFERENCES price(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paytype (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL UNIQUE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS worktype (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL UNIQUE,
  no INT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workgroup (
  id SERIAL PRIMARY KEY,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  worktype_id INT NOT NULL REFERENCES worktype(id) ON DELETE RESTRICT,
  workcount INT NOT NULL,
  description TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS work (
  id SERIAL PRIMARY KEY,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  worker_id INT NOT NULL REFERENCES worker(id) ON DELETE CASCADE,
  worktype_id INT NOT NULL REFERENCES worktype(id) ON DELETE RESTRICT,
  workgroup_id INT NOT NULL REFERENCES workgroup(id) ON DELETE CASCADE,
  description TEXT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment (
  id SERIAL PRIMARY KEY,
  worker_id INT NOT NULL REFERENCES worker(id) ON DELETE CASCADE,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  paytype_id INT NOT NULL REFERENCES paytype(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice (
  id SERIAL PRIMARY KEY,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO employer (fname, lname, tel, description)
SELECT 'JOHN', 'DOE', ARRAY['+90 555 111 11 11'], 'DEFAULT EMPLOYER'
WHERE NOT EXISTS (SELECT 1 FROM employer);

INSERT INTO worker (fname, lname, tel, iban, description)
SELECT 'JANE', 'SMITH', ARRAY['+90 555 222 22 22'], 'TR000000000000000000000001', 'DEFAULT WORKER'
WHERE NOT EXISTS (SELECT 1 FROM worker);

INSERT INTO price (fulltime, halftime, overtime)
SELECT 1000.00, 500.00, 1500.00
WHERE NOT EXISTS (SELECT 1 FROM price);

INSERT INTO paytype (title)
SELECT 'CASH'
WHERE NOT EXISTS (SELECT 1 FROM paytype WHERE title = 'CASH');

INSERT INTO paytype (title)
SELECT 'BANK TRANSFER'
WHERE NOT EXISTS (SELECT 1 FROM paytype WHERE title = 'BANK TRANSFER');

INSERT INTO worktype (title, no)
SELECT 'STANDARD', 1
WHERE NOT EXISTS (SELECT 1 FROM worktype WHERE title = 'STANDARD');

INSERT INTO job (employer_id, price_id, title, description)
SELECT e.id, p.id, 'SAMPLE JOB', 'DEFAULT JOB FOR UI LISTS'
FROM employer e
CROSS JOIN price p
WHERE NOT EXISTS (SELECT 1 FROM job)
LIMIT 1;

GRANT USAGE ON SCHEMA public TO "Hesap-eProject";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "Hesap-eProject";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "Hesap-eProject";
